### PR TITLE
fixes #5: don't close stream while paused

### LINKED ISSUE #5: closing a readable stream while paused
If a read stream is paused in a data event and asynchronically resumed, the close event might happen before the stream is resumed.

See https://github.com/Level/levelup/issues/359 for further details.

### PR DESCRIPTION
**Pull request by timkuijsten**
if a stream is paused, wait until a stream is resumed before emitting close.

### CODE REVIEW

**Comment by dominictarr** [comment]
:+1: i think this should be correct behavior.

**Comment by mcollina** [comment]
The test you wrote it is failing on Travis. Can you have a look?

**Comment by timkuijsten** [comment]
@mcollina yes, one test is failing, but that was already the case without my patch..

**Comment by mcollina** [comment]
I'm :+1:. Any other opinions? @mafintosh?

**Comment by juliangruber** [comment]
i wonder why this isn't the default with streams3...

**Comment by mafintosh** [comment]
:-1: close is (usually) used to indicate the stream is discarded/destroyed and shouldn't wait for back pressure mechanics. I would listen for `end` if i wanted to make sure the stream was unpaused and drained.

This opens up for potential hard-to-catch leaks if a writable stream you are piping to ends prematurely whilst being paused

``` js
iteratorStream.pipe(serializer).pipe(httpResponse)
httpResponse.on('close', function () {
  // the http response ended premature
  iteratorStream.destroy() // might *not* destroy the stream now if it was paused
})
```

The above scenario might happen if a http response times out for example

**Comment by timkuijsten** [comment]
> I would listen for end if i wanted to make sure the stream was unpaused and drained.

@mafintosh It currently doesn't work with end either (still a premature close with the original code). You mean adding an end event after close to the code?

**Comment by juliangruber** [comment]
i'd be surprised if `end` gets emitted early

**Comment by juliangruber** [comment]
@mafintosh thanks for the explanation, i agree it makes sense the way it is currently

**Comment by juliangruber** [comment]
@timkuijsten maybe the simplest solution is to write a module that calls a callback when a stream's `end` and `close` events have been fired, if that's what you're after

**Comment by timkuijsten** [comment]
@juliangruber well, I'm currently working around it by checking in the [data event](https://github.com/Netsend/mastersync/blob/level/lib/tree.js#L773) as well as [on close](https://github.com/Netsend/mastersync/blob/level/lib/tree.js#L779) if I'm still processing a data event (but maybe I can replace that with end-of-stream, tnx @mafintosh).

It still feels as something that should be fixed in this module instead of by the users using this module (or maybe even in core streams). +1 for "we really need to add properly defined destruction events/methods at some point to core streams to fix this mess"

**Comment by juliangruber** [comment]
hm, why do you need the close event anyway? does end not work for you?

**Comment by timkuijsten** [comment]
@juliangruber end also emits right after the last data event is emitted, whether it's paused or not.

**Comment by juliangruber** [comment]
but when it's paused no data events are emitted

**Comment by timkuijsten** [comment]
If I pause the stream when the last data event is emitted, the close (or end) will follow right away, before I even resumed the stream. See the test that I've added: https://github.com/timkuijsten/iterator-stream/blob/gh5/test.js#L91 Both "close" and "end" emit even if a stream is paused. "i" in the test at L92 will be 2 instead of 3.

**Comment by juliangruber** [comment]
that's how node streams work, i don't see a reason in changing that here

**Comment by dominictarr** [comment]
@mafintosh you may well be right that the underlying resources may be disposed of before the stream has ended, but are there any actual cases, like, in node core, where streams behave that way? Things get way complicated if you must handle two types of end.

Hmm, @mafintosh is probably right that you should listen to end and not close... what effect does emitting close early have? does it break piping?

**Comment by timkuijsten** [comment]
I tried to rework the patch to only emit end after a stream is resumed, but it looks like it emits right after this.push(null) whether or not I'll emit another "end" later on. Is there a way to prevent the end event from emitting right after this.push(null)? Otherwise it will have the same "when the underlying resource has been closed" semantics as "close".

**Comment by mafintosh** [comment]
@dominictarr emitting close early has no effect in streams3 readable streams. Here is a core example using http where close gets emitted before end

``` js
var http = require('http')

http.createServer(function (req, res) {
  req.on('close', function () {
    console.log('on close')
  })
  req.on('end', function () {
    console.log('on end')
  })
}).listen(9000)
```

Run `curl localhost:9000` and then `ctrl-c` the curl process

**Comment by mafintosh** [comment]
@timkuijsten `end` is emitted as soon as the read buffer is empty after `.push(null)` (this is core streams behaviour)

**Comment by timkuijsten** [comment]
@mafintosh so I guess there is no way to postpone *end* until a paused stream is resumed?

**Comment by mafintosh** [comment]
@timkuijsten i guess not if there is no data left in the buffer. you should open an issue on https://github.com/nodejs/readable-stream describing your use case

**Comment by timkuijsten** [comment]
@mafintosh alright, tnx for the insights.

**Comment by timkuijsten** [comment]
ps. the aforementioned `end-of-stream` is not a solution for this problem.

**Comment by dominictarr** [comment]
@mafintosh in your example, close is emitted _but end is not!_.
in classic streams, close called destroy on the dest, making close effectively another kind of end.
Meaning, the stream has ended, but not successfully... reading the code, `close' event does cause a readable stream to disconnect: https://github.com/nodejs/node/blob/master/lib/_stream_readable.js#L554-L557

**Comment by dominictarr** [comment]
that isn't the same as .destroy() but it is not the same as doing nothing.

**Comment by mafintosh** [comment]
@dominictarr yes you are right but that is only if the stream you are writing *to* emits `close` though. if the readable part emits `close` nothing happens AFAIK

**Comment by dominictarr** [comment]
@mafintosh ah you are right, that is `dest.on('close',...)`.

**Comment by mafintosh** [comment]
@dominictarr 

``` js
var http = require('http')

http.createServer(function (req, res) {
  req.on('close', function () {
    console.log('on close')
    // this is contrived but could happen if we we're piping somewhere
    // and then experienced a premature close
    req.resume()
  })
  req.on('end', function () {
    console.log('on end')
  })
}).listen(9000)
```

Try running this example and ctrl-c the curl process like before :)

**Pull request closed without merging**
