### PR TITLE
Use nodejs-builtin stream if available

### PR DESCRIPTION
**Pull request by heri16**

### CODE REVIEW

**Comment by ralphtheninja** [comment]
We want to use user land so we know we're consistent, see https://github.com/Level/level-ws/issues/37 as well

cc @vweevers

**Comment by vweevers** [comment]
> We want to use user land so we know we're consistent

Oh yes, I would even say *we must*.

@heri16 can you please explain the problem you're facing, so that we can find a different solution?

**Comment by heri16** [comment]
what is the performance of userland? I'm on nodejs v8.10 on AWS Lambda and getting better performance from native stream. Also would like to reduce the size of my deployment package.

**Comment by vweevers** [comment]
> what is the performance of userland? I'm on nodejs v8.10 on AWS Lambda and getting better performance from native stream. Also would like to reduce the size of my deployment package.

Our version of `readable-stream` (^2.0.5) is a mirror of streams of node 8.11.1. I'm not aware of performance differences between userland and core (cc @mcollina ?).

As for package size, code bundlers like browserify or webpack (in "node mode") can help *a lot*. I often do this for AWS Lambda functions (recently, I had a function that was reduced from 22MB to 900kb). It also improves startup time.

**Comment by heri16** [comment]
Yes, we do intend to explicitly exclude readable-stream in our webpack config. In fact we found an environmental flag that readable.js reads to that allows us to use the built-in implementation. Would setting this flag have any impact on stability if we pimmed on just one version of nodejs?

How unstable are the kernel-land streams API these days? node 0.10 was like released 4 years ago? it's not even LTS? Are there any changes between node v4 till node v10? Or are we just playing safe in case of future changes?

**Comment by heri16** [comment]
Since 2014 was expecting more "userland" libraries to be released by the nodejs foindation. For example for other parts of nodejs core which had some API enhancements over the years. That didn't seem to happen. Today we have only "readable-streams" as the only "userland" library. What happened?

**Comment by vweevers** [comment]
> In fact we found an environmental flag that readable.js reads that allows us to use the built-in implementation. Would setting this flag have any impact on stability if we are pinned on just one modern LTS version of nodejs?

That entirely depends on how you use `level-iterator-stream`, so hard to say. I wouldn't recommend it, unless the performance differences are really that significant and it is worth the risk to you. If they are, please do share some numbers :) Perhaps in the `readable-stream` repo.

> Are there any changes between node v4 till node v10?

Among other things, in node 6 `#write(null)` became invalid, node 8 has `#destroy()`, node 10 has `#pipeline()`, `#finished()`, `Symbol.asyncIterator` and timing changes. Not to mention bug fixes.

> Today we have only "readable-streams" as the only "userland" library, with more of 3rd-party polyfills and backfills. What happened?

That's a discussion to be had elsewhere.

**Comment by vweevers** [comment]
I think everything that is relevant to `level-iterator-stream` has been said, so I'm closing this.

**Comment by heri16** [comment]
Alright. Thanks for your time.

**Pull request closed without merging**
